### ISSUE TITLE
[JOSS review] Community guidelines

### ISSUE THREAD

**Issue by jakelangham** [jcorbino/mole#17]
This issue is part of the ongoing reviews at https://github.com/openjournals/joss-reviews/issues/6288, 

I am trying to check if there are '... clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support'.

I can see that there is a CONTRIBUTING.md file which could count for point 1). However, I would be more comfortable ticking off this bullet point if there were a section on the main page (README.md) that briefly pointed any users in the right direction for (1-3).

**Comment by jcorbino** [comment]
@jakelangham - I appreciate you bringing this to my attention. I've just completed the necessary changes for this specific issue.

**Comment by jakelangham** [comment]
@jcorbino Fantastic - closing this.
